### ISSUE TITLE
[Post Template] Gutenberg 18.2 .alignfull fix breaks existing spacing solution

### ISSUE THREAD

**Issue by justintadlock** [x3p0-dev/x3p0-ideas#10]
A fix in Gutenberg 18.2 breaks the nested Post Template full alignment fix that we had in place. See:

- https://github.com/WordPress/gutenberg/pull/60716

The theme previously fixed this by overruling the margins in the editor so that they matched the front end: https://github.com/x3p0-dev/x3p0-ideas/blob/82330c8277ea5b02e8d191b55b0f07bc3504fbcb/resources/scss/blocks/core/post-template.scss#L35-L42

The Core/Gutenberg fix takes this in the opposite direction by making the front end match the editor. Unfortunately, this presents a problem with how the theme lays out pretty much most of its Query Loop / Post Template patterns. 

The most obvious fix would be to re-add a wrapping Group block inside the Query Loop that wraps Post Template. But that solution results in the _divitis_ that I worked so hard to get rid of.

Another solution might be to update the theme's CSS to work on both the front end and editor, but do I really want to spend my time fighting Core/Gutenberg? 

🤔

**Comment by justintadlock** [comment]
It's worth noting the biggest problem has always been that there's no way to add padding to the Post Template block itself by default, so it may be worth exploring adding that.

**Comment by justintadlock** [comment]
Some further investigation reveals that the `.has-global-padding` handling is inconsistent if I remove left/right padding from the outer Query Loop block in this situation.

- Editor: adds global padding to the outer Query Loop.
- Front End: zeroes out global padding on the outer Query Loop.

Almost thought this would be an easy fix.

**Comment by webmandesign** [comment]
Maybe, [it would be great if a theme has some control over the CSS produced](https://github.com/WordPress/gutenberg/pull/60716#pullrequestreview-2088156878).

**Comment by justintadlock** [comment]
The last remnants of this should've been addressed with this change to the Query List Cover pattern: https://github.com/x3p0-dev/x3p0-ideas/commit/a0b5b8de43bec8e0af401d90ec25f381f52e2155
